import type { Component } from 'solid-js'
import type { InputPickerDef, ValuePickerDef } from '../components/ui'
import { WidgetType } from './widget'
import * as Widget from '../components/widgets'

export const WidgetTypeMap:{[key:number]:Component} = {
	[WidgetType.StickCircle]:			Widget.WStickCircle,
	[WidgetType.StickSquare]:			Widget.WStickSquare,
	[WidgetType.StickGC]:				Widget.WStickGC,
	[WidgetType.StickN64]:				Widget.WStickN64,
	[WidgetType.StickHori]:				Widget.WStickHori,
	[WidgetType.StickRound]:			Widget.WStickRound,
	[WidgetType.Stick]:					Widget.WStick,
	[WidgetType.Button]:				Widget.WButton,
	[WidgetType.ButtonRing]:			Widget.WButtonRing,
	[WidgetType.ButtonRingCircle]:		Widget.WButtonRingCircle,
	[WidgetType.ButtonRingRect]:		Widget.WButtonRingRect,
	[WidgetType.ButtonRingTriangle]:	Widget.WButtonRingTriangle,
	[WidgetType.ButtonRingN64C]:		Widget.WButtonRingN64C,
	[WidgetType.ButtonRingGCXY]:		Widget.WButtonRingGCXY,
	[WidgetType.ButtonGrid]:			Widget.WButtonGrid,
	[WidgetType.ButtonGridCircle]:		Widget.WButtonGridCircle,
	[WidgetType.ButtonGridRect]:		Widget.WButtonGridRect,
	[WidgetType.ButtonGridTriangle]:	Widget.WButtonGridTriangle,
	[WidgetType.ButtonGridN64C]:		Widget.WButtonGridN64C,
	[WidgetType.ButtonGridGCXY]:		Widget.WButtonGridGCXY,
	[WidgetType.DPad]:					Widget.WDPad,
	[WidgetType.Trigger]:				Widget.WTrigger,
	[WidgetType.TriggerCurved]:			Widget.WTriggerCurved,
	[WidgetType.TriggerFlat]:			Widget.WTriggerFlat,
} as const

export const WidgetInputDefMap:{[key:number]:InputPickerDef} = {
	[WidgetType.StickCircle]:			Widget.StickInputGroupDef,
	[WidgetType.StickSquare]:			Widget.StickInputGroupDef,
	[WidgetType.StickGC]:				Widget.StickInputGroupDef,
	[WidgetType.StickN64]:				Widget.StickInputGroupDef,
	[WidgetType.StickHori]:				Widget.StickInputGroupDef,
	[WidgetType.StickRound]:			Widget.StickInputGroupDef,
	[WidgetType.Stick]:					Widget.StickInputGroupDef,
	[WidgetType.Button]:				Widget.ButtonInputGroupDef,
	[WidgetType.ButtonRing]:			Widget.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingCircle]:		Widget.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingRect]:		Widget.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingTriangle]:	Widget.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingN64C]:		Widget.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingGCXY]:		Widget.ButtonRingInputGroupDef,
	[WidgetType.ButtonGrid]:			Widget.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridCircle]:		Widget.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridRect]:		Widget.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridTriangle]:	Widget.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridN64C]:		Widget.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridGCXY]:		Widget.ButtonGridInputGroupDef,
	[WidgetType.DPad]:					Widget.DPadInputGroupDef,
	[WidgetType.Trigger]:				Widget.TriggerInputGroupDef,
	[WidgetType.TriggerCurved]:			Widget.TriggerInputGroupDef,
	[WidgetType.TriggerFlat]:			Widget.TriggerInputGroupDef,
} as const

export const WidgetValueDefMap:{[key:number]:ValuePickerDef} = {
	[WidgetType.StickCircle]:			Widget.StickShapeValueDef,
	[WidgetType.StickSquare]:			Widget.StickShapeValueDef,
	[WidgetType.StickGC]:				Widget.StickShapeValueDef,
	[WidgetType.StickN64]:				Widget.StickShapeValueDef,
	[WidgetType.StickHori]:				Widget.StickShapeValueDef,
	[WidgetType.StickRound]:			Widget.StickShapeValueDef,
	[WidgetType.Stick]:					Widget.StickValueDef,
	[WidgetType.Button]:				Widget.ButtonValueDef,
	[WidgetType.ButtonRing]:			Widget.ButtonRingValueDef,
	[WidgetType.ButtonRingCircle]:		Widget.ButtonRingCircleValueDef,
	[WidgetType.ButtonRingRect]:		Widget.ButtonRingRectValueDef,
	[WidgetType.ButtonRingTriangle]:	Widget.ButtonRingTriangleValueDef,
	[WidgetType.ButtonRingN64C]:		Widget.ButtonRingN64CValueDef,
	[WidgetType.ButtonRingGCXY]:		Widget.ButtonRingGCXYValueDef,
	[WidgetType.ButtonGrid]:			Widget.ButtonGridValueDef,
	[WidgetType.ButtonGridCircle]:		Widget.ButtonGridCircleValueDef,
	[WidgetType.ButtonGridRect]:		Widget.ButtonGridRectValueDef,
	[WidgetType.ButtonGridTriangle]:	Widget.ButtonGridTriangleValueDef,
	[WidgetType.ButtonGridN64C]:		Widget.ButtonGridN64CValueDef,
	[WidgetType.ButtonGridGCXY]:		Widget.ButtonGridGCXYValueDef,
	[WidgetType.DPad]:					Widget.DPadValueDef,
	[WidgetType.Trigger]:				Widget.TriggerValueDef,
	[WidgetType.TriggerCurved]:			Widget.TriggerValueDef,
	[WidgetType.TriggerFlat]:			Widget.TriggerFlatValueDef,
} as const
