import type { Component } from 'solid-js'
import type { InputPickerDef, ValuePickerDef } from '../components/ui'
import { WidgetType } from './widget'
import * as Widget from '../components/widgets'
import * as Input from '../components/inputs'

export const WidgetTypeMap:{[key:number]:Component} = {
	[WidgetType.StickCircle]:			Widget.WStickCircle,
	[WidgetType.StickSquare]:			Widget.WStickSquare,
	[WidgetType.StickGC]:				Widget.WStickGC,
	[WidgetType.StickN64]:				Widget.WStickN64,
	[WidgetType.StickHori]:				Widget.WStickHori,
	[WidgetType.StickRound]:			Widget.WStickRound,
	[WidgetType.Stick]:					Widget.WStick,
	[WidgetType.Button]:				Widget.WButton,
	[WidgetType.ButtonRing]:			Widget.WButtonRing,
	[WidgetType.ButtonRingCircle]:		Widget.WButtonRingCircle,
	[WidgetType.ButtonRingRect]:		Widget.WButtonRingRect,
	[WidgetType.ButtonRingTriangle]:	Widget.WButtonRingTriangle,
	[WidgetType.ButtonRingN64C]:		Widget.WButtonRingN64C,
	[WidgetType.ButtonRingGCXY]:		Widget.WButtonRingGCXY,
	[WidgetType.ButtonGrid]:			Widget.WButtonGrid,
	[WidgetType.ButtonGridCircle]:		Widget.WButtonGridCircle,
	[WidgetType.ButtonGridRect]:		Widget.WButtonGridRect,
	[WidgetType.ButtonGridTriangle]:	Widget.WButtonGridTriangle,
	[WidgetType.ButtonGridN64C]:		Widget.WButtonGridN64C,
	[WidgetType.ButtonGridGCXY]:		Widget.WButtonGridGCXY,
	[WidgetType.DPad]:					Widget.WDPad,
	[WidgetType.Trigger]:				Widget.WTrigger,
	[WidgetType.TriggerCurved]:			Widget.WTriggerCurved,
	[WidgetType.TriggerFlat]:			Widget.WTriggerFlat,
} as const

export const WidgetInputDefMap:{[key:number]:InputPickerDef} = {
	[WidgetType.StickCircle]:			Input.StickInputGroupDef,
	[WidgetType.StickSquare]:			Input.StickInputGroupDef,
	[WidgetType.StickGC]:				Input.StickInputGroupDef,
	[WidgetType.StickN64]:				Input.StickInputGroupDef,
	[WidgetType.StickHori]:				Input.StickInputGroupDef,
	[WidgetType.StickRound]:			Input.StickInputGroupDef,
	[WidgetType.Stick]:					Input.StickInputGroupDef,
	[WidgetType.Button]:				Input.ButtonInputGroupDef,
	[WidgetType.ButtonRing]:			Input.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingCircle]:		Input.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingRect]:		Input.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingTriangle]:	Input.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingN64C]:		Input.ButtonRingInputGroupDef,
	[WidgetType.ButtonRingGCXY]:		Input.ButtonRingInputGroupDef,
	[WidgetType.ButtonGrid]:			Input.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridCircle]:		Input.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridRect]:		Input.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridTriangle]:	Input.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridN64C]:		Input.ButtonGridInputGroupDef,
	[WidgetType.ButtonGridGCXY]:		Input.ButtonGridInputGroupDef,
	[WidgetType.DPad]:					Input.DPadInputGroupDef,
	[WidgetType.Trigger]:				Input.TriggerInputGroupDef,
	[WidgetType.TriggerCurved]:			Input.TriggerInputGroupDef,
	[WidgetType.TriggerFlat]:			Input.TriggerInputGroupDef,
} as const

export const WidgetValueDefMap:{[key:number]:ValuePickerDef} = {
	[WidgetType.StickCircle]:			Input.StickShapeValueDef,
	[WidgetType.StickSquare]:			Input.StickShapeValueDef,
	[WidgetType.StickGC]:				Input.StickShapeValueDef,
	[WidgetType.StickN64]:				Input.StickShapeValueDef,
	[WidgetType.StickHori]:				Input.StickShapeValueDef,
	[WidgetType.StickRound]:			Input.StickShapeValueDef,
	[WidgetType.Stick]:					Input.StickValueDef,
	[WidgetType.Button]:				Input.ButtonValueDef,
	[WidgetType.ButtonRing]:			Input.ButtonRingValueDef,
	[WidgetType.ButtonRingCircle]:		Input.ButtonRingCircleValueDef,
	[WidgetType.ButtonRingRect]:		Input.ButtonRingRectValueDef,
	[WidgetType.ButtonRingTriangle]:	Input.ButtonRingTriangleValueDef,
	[WidgetType.ButtonRingN64C]:		Input.ButtonRingN64CValueDef,
	[WidgetType.ButtonRingGCXY]:		Input.ButtonRingGCXYValueDef,
	[WidgetType.ButtonGrid]:			Input.ButtonGridValueDef,
	[WidgetType.ButtonGridCircle]:		Input.ButtonGridCircleValueDef,
	[WidgetType.ButtonGridRect]:		Input.ButtonGridRectValueDef,
	[WidgetType.ButtonGridTriangle]:	Input.ButtonGridTriangleValueDef,
	[WidgetType.ButtonGridN64C]:		Input.ButtonGridN64CValueDef,
	[WidgetType.ButtonGridGCXY]:		Input.ButtonGridGCXYValueDef,
	[WidgetType.DPad]:					Input.DPadValueDef,
	[WidgetType.Trigger]:				Input.TriggerValueDef,
	[WidgetType.TriggerCurved]:			Input.TriggerValueDef,
	[WidgetType.TriggerFlat]:			Input.TriggerFlatValueDef,
} as const
